/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TextingChatIdImport } from './routes/texting/$chatId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TextingChatIdRoute = TextingChatIdImport.update({
  path: '/texting/$chatId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/texting/$chatId': {
      id: '/texting/$chatId'
      path: '/texting/$chatId'
      fullPath: '/texting/$chatId'
      preLoaderRoute: typeof TextingChatIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/texting/$chatId': typeof TextingChatIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/texting/$chatId': typeof TextingChatIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/texting/$chatId': typeof TextingChatIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/texting/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/texting/$chatId'
  id: '__root__' | '/' | '/texting/$chatId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TextingChatIdRoute: typeof TextingChatIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TextingChatIdRoute: TextingChatIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/texting/$chatId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/texting/$chatId": {
      "filePath": "texting/$chatId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
